{'author': 'Nedas Zilinskas',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['security/ir.model.access.csv',
          'views/assets.xml',
          'views/snippet.xml',
          'views/website_embed.xml'],
 'demo': [],
 'depends': ['website'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/website_embed/12.0',
 'name': 'Embed HTML Building Block',
 'price': 35.0,
 'qweb': [],
 'summary': 'Embed HTML snippets to your website',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '12.0.1.0.0',
 'website': 'https://demo.minilini.com'}

